[tests] Set --output-dir on all test runs, in support of running tests in parallel.
 - It would be nice if there was an easier way to do this that didn't involve
   editing all of the tests (like running each test in its own directory), but
   this approach fixes #146 and doesn't involve changing 'lit' or writing a
   wrapper harness. My assumption is a lot of tests start are derived from
   another one, so hopefully following this convention won't be burdensome, and
   I updated 'make check' so that it will produce an error if any test runs klee
   without --output-dir (by checking for the existing of klee-last files).

 - This also helps with #147 but I still can't fully run tests in parallel (I
   start hitting STP errors).

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -49,6 +49,11 @@ LIT_ALL_TESTSUITES := $(LIT_TESTSUITE)
 check-local:: lit.site.cfg
 	$(Verb) ( $(ULIMIT) \
 	          $(PYTHON) $(LLVM_SRC_ROOT)/utils/lit/lit.py $(LIT_ARGS) $(LIT_TESTSUITE) )
+	@klee_last_path=$$(find . -name klee-last | head -1); \
+	 if [ ! -z "$$klee_last_path" ]; then \
+	  echo "error: one of the tests failed to use --output-dir, found: $$klee_last_path"; \
+	  exit 1; \
+	fi
 
 check-local-all:: lit.site.cfg
 	$(Verb) ( $(ULIMIT) \
